import type { Metadata } from "next";
import { manrope } from "./fonts";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: "Bookmark Manager",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} subpixel-antialiased`}
      >
        <ThemeProvider enableSystem={false}>
          <NuqsAdapter>
            <div className="bg-accent-secondary h-screen">
              {children}
            </div>
          </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
