import type { Metadata } from "next";
import { manrope } from "./fonts";
import "./globals.css";
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} subpixel-antialiased`}
      >
        <ThemeProvider enableSystem={false}>
          <div className="bg-neutral-100 h-screen">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
